### ISSUE TITLE
WP 4.3 breaks textorum [Annotum]

### ISSUE THREAD

**Issue by dregula** [Annotum/textorum#2] opened 2015-09-08 04:03 UTC
WP 4.2 works fine. The latest upgrade, WP4.3, breaks the textorum editor for articles.
The third line from my Chrome javascript console shows a fatal exception (below.)
Thanks in advance.
-Don
Deprecated TinyMCE API call: <target>.onInit.add(..)
wp-tinymce.php?c=1&ver=4203-20150730:11 Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check http://xhr.spec.whatwg.org/.
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,heartbeat,autosave,suggest,jquery-ui-c…:2 Uncaught Error: Syntax error, unrecognized expression: &lt;div data-textorum-nsurl=&quot;http://www.w3.org/XML/1998/namespace&quot; data-textorum-nsprefix=&quot;xml&quot;&gt;&lt;/div&gt;&lt;div class=&quot;p&quot; data-xmlel=&quot;p&quot;&gt; &lt;/div&gt;

**Comment by carlthewebmaster** [comment] 2015-09-08 12:28
This is a duplicate of https://github.com/Annotum/Annotum/issues/228

**Closed as completed by carlthewebmaster** 2015-09-08 12:28 UTC
